using System;

namespace BinaryStudio.Modeling.UnifiedModelingLanguage
    {
    /// <summary>
    /// This is an enumerated type that identifies the type of communication action that was used to generate the <see cref="Message"/>.
    /// </summary>
    /// xmi:id="MessageSort"
    public enum MessageSort
        {
        /// <summary>
        /// The message was generated by a synchronous call to an operation.
        /// </summary>
        /// xmi:id="MessageSort-synchCall"
        SynchCall,
        /// <summary>
        /// The message was generated by an asynchronous call to an operation; i.e., a <see cref="CallAction"/> with isSynchronous = false.
        /// </summary>
        /// xmi:id="MessageSort-asynchCall"
        AsynchCall,
        /// <summary>
        /// The message was generated by an asynchronous send action.
        /// </summary>
        /// xmi:id="MessageSort-asynchSignal"
        AsynchSignal,
        /// <summary>
        /// The message designating the creation of another lifeline object.
        /// </summary>
        /// xmi:id="MessageSort-createMessage"
        CreateMessage,
        /// <summary>
        /// The message designating the termination of another lifeline.
        /// </summary>
        /// xmi:id="MessageSort-deleteMessage"
        DeleteMessage,
        /// <summary>
        /// The message is a reply message to an operation call.
        /// </summary>
        /// xmi:id="MessageSort-reply"
        Reply
        }
    }
